sudo: required
services:
  - docker

before_install:
  - docker build -t rohityadav007/docker-react-web -f Dockerfile.dev .

script:
  - docker run -e CI=true rohityadav007/docker-react-web npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "DockerReactWeb-env"
  env: "DockerreactwebEnv-env"
  bucket_name: "elasticbeanstalk-eu-central-1-097350876455"
  bucket_path: "DockerReactWeb-env"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
