sudo: required
services:
  - docker

before_install:
  - docker build -t rohityadav007/docker-react-web -f Dockerfile.dev .

script:
  - docker run -e CI=true rohityadav007/docker-react-web npm run test
